[Paths]
Prefix=$PREFIX
ArchData=lib/$TRIPLET/qt5
Binaries=lib/qt5/bin
Data=share/qt5
Documentation=share/qt5/doc
Headers=include/$TRIPLET/qt5
HostBinaries=lib/qt5/bin
HostData=lib/$TRIPLET/qt5
HostLibraries=lib/$TRIPLET
Libraries=lib/$TRIPLET
LibraryExecutables=lib/qt5/libexec
HostLibraryExecutables=lib/qt5/libexec
Plugins=lib/$TRIPLET/qt5/plugins
Qml2Imports=lib/$TRIPLET/qt5/qml
Settings=/etc/xdg
Translations=share/qt5/translations
